In [3]:
import numpy as np
A1=[1,3,5,7,11,13,17]
a=np.array(A1)
print(a)

[ 1  3  5  7 11 13 17]


In [6]:
A2=[10,20],[30,40],[11,22],[44,88]
b=np.array(A2)
print(b)
print(A2)

[[10 20]
 [30 40]
 [11 22]
 [44 88]]
([10, 20], [30, 40], [11, 22], [44, 88])


In [7]:
a.ndim

1

In [8]:
b.ndim

2

In [9]:
a.itemsize

4

In [10]:
b.itemsize

4

In [11]:
c=np.array([1.2,4.5,6.7,8.9,3,5])
c.itemsize

8

In [12]:
b.dtype

dtype('int32')

In [13]:
c.dtype

dtype('float64')

In [18]:
e=np.empty(5)
e

array([0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 5.0197070e-321,
       7.5660388e-307])

In [19]:
ei=np.empty(5,dtype=np.int)
ei

array([0, 0, 0, 0, 0])

In [20]:
er=np.random.random(6)
er

array([0.61345281, 0.13827599, 0.14521748, 0.35086259, 0.54638263,
       0.55097762])

In [5]:
import numpy as np
arr=np.array([[-1,4,0,5],
             [3,6,8,-2],
             [3,4,7,-1],
             [-7,-2,9,0]])
print(arr)
t=arr[::,::2]    #1st part is rows & 2nd part is columns
print(t)
print()
print("Transpose of array")
print(arr.T)

[[-1  4  0  5]
 [ 3  6  8 -2]
 [ 3  4  7 -1]
 [-7 -2  9  0]]
[[-1  0]
 [ 3  8]
 [ 3  7]
 [-7  9]]

Transpose of array
[[-1  3  3 -7]
 [ 4  6  4 -2]
 [ 0  8  7  9]
 [ 5 -2 -1  0]]


In [9]:
arr=np.array([[-10,43,100,59],
             [453,566,18,-92],
             [43,46,79,-11],
             [-57,-62,96,95]])
print(arr.max(axis=1))
print(arr.max(axis=0))

[100 566  79  96]
[453 566 100  95]


In [15]:
arr=np.array([[-1,4,10,5],
             [3,6,8,2],
             [3,4,7,1],
             [7,-2,9,0]])
print(arr.sum())
print(arr.cumsum(axis=1))    #axis=1 for rows
print(arr.cumsum(axis=0))    #axis=0 for columns

66
[[-1  3 13 18]
 [ 3  9 17 19]
 [ 3  7 14 15]
 [ 7  5 14 14]]
[[-1  4 10  5]
 [ 2 10 18  7]
 [ 5 14 25  8]
 [12 12 34  8]]


In [17]:
print(np.sort(arr,axis=None))
print(np.sort(arr,axis=0))    #For columns
print(np.sort(arr,axis=1))    #For rows

[-2 -1  0  1  2  3  3  4  4  5  6  7  7  8  9 10]
[[-1 -2  7  0]
 [ 3  4  8  1]
 [ 3  4  9  2]
 [ 7  6 10  5]]
[[-1  4  5 10]
 [ 2  3  6  8]
 [ 1  3  4  7]
 [-2  0  7  9]]


In [18]:
print(np.sort(arr))    #By default considers row

[[-1  4  5 10]
 [ 2  3  6  8]
 [ 1  3  4  7]
 [-2  0  7  9]]


In [19]:
print(arr[1,-1])

2


In [22]:
a=np.array([12,45,213,56,78,34,67,90,78])
newarr=np.array_split(a,3)
print(newarr)
len(newarr)

[array([ 12,  45, 213]), array([56, 78, 34]), array([67, 90, 78])]


3

In [28]:
arr=np.array([1,3,4,2,4,5,3,4])
x=np.where(arr==3)
print(x)

(array([1, 6], dtype=int32),)


In [29]:
arr=np.array([1,3,4,5,7,8,10])
x=np.searchsorted(arr,7)
print(x)

4


In [30]:
ar=np.array([34,56,12,9,560])
print(np.sort(ar))

[  9  12  34  56 560]


In [31]:
ach=np.array(["mango","cherry","banana","apple"])
print(np.sort(ach))

['apple' 'banana' 'cherry' 'mango']


In [35]:
arr=np.array([[1,2,4],[5,0,1]])
print(np.sort(arr,axis=None))

[0 1 1 2 4 5]
